ContainerAppSystemLogs_CL
| where TimeGenerated > ago(10m)
| where ContainerAppName_s == '__WEB_NAME__'
| where Reason_s == 'ProbeFailed'
| where Log_s startswith 'Probe of Readiness failed'
    or Log_s contains 'failed readiness probe'
    or Log_s startswith 'Readiness Probe of Readiness reached failure threshold'
    or Log_s contains 'readiness probe failed'
| summarize FirstFailure = min(TimeGenerated), LastFailure = max(TimeGenerated) by RevisionName_s
| where LastFailure - FirstFailure >= 5m and LastFailure > ago(2m)
| project RevisionName_s, FirstFailure, LastFailure
