import type { Policies, Catalog } from '../../api/accounting';
import { AccountingField, type FieldErrors } from './AccountingField';
export function PolicyFields({ value, catalog, change, errors = {} }: { value: Policies; catalog: Catalog; change(value: Policies): void; errors?: FieldErrors }) {
  function set(key: keyof Policies, next: string | number | null) { change({ ...value, [key]: next }); }
  const country = catalog.countries.find(item => item.code === value.country);
  return <div className="accounting-policy-groups">
    <fieldset className="accounting-policy-group"><legend>Location and currency</legend><div className="accounting-grid">
      <AccountingField field="policies.country" label="Country" errors={errors}>{attributes => <select {...attributes} value={value.country ?? ''} onChange={e => change({ ...value, country: e.target.value || null, region: null })}><option value="">Choose country</option>{catalog.countries.map(item => <option key={item.code} value={item.code}>{item.name}</option>)}</select>}</AccountingField>
      <AccountingField field="policies.region" label="State or region" errors={errors}>{attributes => <select {...attributes} value={value.region ?? ''} disabled={!country?.regions.length} onChange={e => set('region', e.target.value || null)}><option value="">{country?.regions.length ? 'Choose region' : 'Not applicable'}</option>{country?.regions.map(item => <option key={item.code} value={item.code}>{item.name}</option>)}</select>}</AccountingField>
      <AccountingField field="policies.currency" label="Functional currency" errors={errors}>{attributes => <select {...attributes} value={value.currency ?? ''} onChange={e => set('currency', e.target.value || null)}><option value="">Choose currency</option>{catalog.currencies.map(item => <option key={item.code} value={item.code}>{item.code} — {item.name}</option>)}</select>}</AccountingField>
      <AccountingField field="policies.scale" label="Posting decimal places" errors={errors}>{attributes => <select {...attributes} value={value.scale ?? ''} onChange={e => set('scale', e.target.value === '' ? null : Number(e.target.value))}><option value="">Confirm precision</option>{[0,1,2,3,4].map(scale => <option key={scale}>{scale}</option>)}</select>}</AccountingField>
    </div></fieldset>
    <fieldset className="accounting-policy-group"><legend>Accounting dates</legend><div className="accounting-grid">
      <AccountingField field="policies.fiscalStartMonth" label="Fiscal year starts" errors={errors}>{attributes => <select {...attributes} value={value.fiscalStartMonth ?? ''} onChange={e => set('fiscalStartMonth', e.target.value ? Number(e.target.value) : null)}><option value="">Choose month</option>{Array.from({ length: 12 }, (_, i) => <option key={i} value={i+1}>{new Intl.DateTimeFormat('en', { month: 'long', timeZone: 'UTC' }).format(new Date(Date.UTC(2024,i,1)))}</option>)}</select>}</AccountingField>
      <AccountingField field="policies.startApproach" label="Starting approach" errors={errors} help="Complete history uses your complete business history, starting with the first transaction. Opening balances use verified balances on your planned start date. Saving this choice does not import history or create balances.">{attributes => <select {...attributes} value={value.startApproach ?? ''} onChange={e => set('startApproach', e.target.value || null)}><option value="">Choose approach</option><option value="FromBeginning">Complete history from the beginning</option><option value="OpeningBalances">Reconciled opening balances</option></select>}</AccountingField>
      <AccountingField field="policies.plannedStartDate" label="Planned start date" errors={errors}>{attributes => <input {...attributes} type="date" value={value.plannedStartDate ?? ''} onChange={e => set('plannedStartDate', e.target.value || null)} />}</AccountingField>
    </div></fieldset>
    <fieldset className="accounting-policy-group"><legend>Retention and policy notes</legend><p className="accounting-help">Record how long you propose to keep documents and the reason for that period. Workbench does not yet enforce this retention plan.</p><div className="accounting-grid">
      <AccountingField field="policies.retentionYears" label="Proposed document retention (years)" errors={errors}>{attributes => <input {...attributes} type="number" min="1" max="1000" step="1" value={value.retentionYears ?? ''} onChange={e => set('retentionYears', e.target.value ? Number(e.target.value) : null)} />}</AccountingField>
      <AccountingField field="policies.retentionRationale" label="Retention rationale or reference" errors={errors}>{attributes => <textarea {...attributes} maxLength={2000} value={value.retentionRationale ?? ''} onChange={e => set('retentionRationale', e.target.value || null)} />}</AccountingField>
      <AccountingField field="policies.frameworkNotes" label="Framework and tax policy notes (optional)" errors={errors}>{attributes => <textarea {...attributes} maxLength={2000} value={value.frameworkNotes ?? ''} onChange={e => set('frameworkNotes', e.target.value || null)} />}</AccountingField>
    </div></fieldset>
  </div>;
}
