# Copyright (c) 2026 The White Stag Collection.
#Requires -Version 7.4
$ErrorActionPreference = 'Stop'
$fixture = Join-Path ([IO.Path]::GetTempPath()) ('workbench-update-validation-' + [Guid]::NewGuid().ToString('N'))
$oldPath = $env:PATH
$oldFixture = $env:WB_SETUP_FIXTURE_ROOT
New-Item -ItemType Directory -Path "$fixture/bin" -Force | Out-Null
Copy-Item "$PSScriptRoot/local-self-host/test-docker.ps1" "$fixture/bin/docker.ps1"
try {
    # GIVEN an installation generated by the current setup with simulated Docker.
    $env:PATH = "$fixture/bin;$oldPath"
    $env:WB_SETUP_FIXTURE_ROOT = $fixture
    & "$PSScriptRoot/setup-local-self-host.ps1" -TenantName QA -AdminEmail qa@example.test -InstallationRoot "$fixture/install" -HttpPort 28081 -HttpsPort 28443
    . "$PSScriptRoot/local-self-host/Update.ps1"
    $root = [IO.Path]::GetFullPath("$fixture/install")
    $originalConfig = [IO.File]::ReadAllText("$root/compose.json")
    $originalState = [IO.File]::ReadAllText("$root/installation.json")
    $project = ($originalState | ConvertFrom-Json).Project
    $originalConnections=@{}
    foreach ($role in @('web','worker','maintenance','migrator')) { $originalConnections[$role]=[IO.File]::ReadAllText("$root/secrets/$role-connection") }
    $failures = [Collections.Generic.List[string]]::new()
    $cases = 0
    $foreignNetwork = $false
    $wrongVolumeOwner = $false
    $wrongNetworkOwner = $false
    function Invoke-LocalDocker($Docker, [string[]]$Arguments) {
        if ($Arguments[0] -eq 'volume' -and $Arguments[1] -eq 'inspect') {
            return ConvertTo-Json @{Name=$Arguments[2]; Labels=@{'com.docker.compose.project'=$(if ($wrongVolumeOwner) {'foreign'} else {$project})}}
        }
        if ($Arguments[0] -eq 'network' -and $Arguments[1] -eq 'inspect') {
            $attached = @{'fixture-app'=@{}}
            if ($foreignNetwork) { $attached['foreign-container']=@{} }
            return ConvertTo-Json @{Labels=@{'com.docker.compose.project'=$(if ($wrongNetworkOwner) {'foreign'} else {$project})};Containers=$attached} -Depth 5
        }
        if ($Arguments[0] -eq 'compose' -and $Arguments -contains 'config') { return }
        throw 'Unexpected Docker validation operation.'
    }
    function Get-UpdateContainers($Context) { return @([pscustomobject]@{Id='fixture-app'}) }
    function Assert-UpdateRunning($Context) { }
    function Assert-UpdateConfigurationCurrent($Context) { }
    function Assert-UpdateHttps($Context) { }
    function Test-ValidationCase([string]$Name, [scriptblock]$Change, [bool]$Reject = $true) {
        $script:cases++
        [IO.File]::WriteAllText("$root/compose.json", $originalConfig)
        [IO.File]::WriteAllText("$root/installation.json", $originalState)
        if (Test-Path "$root/update.json") { Remove-Item -LiteralPath "$root/update.json" }
        $config = $originalConfig | ConvertFrom-Json -AsHashtable
        $state = $originalState | ConvertFrom-Json -AsHashtable
        $journal = $null
        foreach ($role in $originalConnections.Keys) { [IO.File]::WriteAllText("$root/secrets/$role-connection",$originalConnections[$role]) }
        $foreignNetwork = $false
        $wrongVolumeOwner = $false
        $wrongNetworkOwner = $false
        . $Change
        Write-UpdateJson $config "$root/compose.json"
        Write-UpdateJson $state "$root/installation.json"
        if ($journal) { Write-UpdateJson $journal "$root/update.json" }
        $before = (Get-FileHash "$root/compose.json").Hash
        $context = @{Root=$root;ComposeFile="$root/compose.json";Docker=@{Source='simulated'}}
        $rejected = $false
        # WHEN validation examines the selected configuration and ownership evidence.
        try { Assert-UpdateInstallation $context } catch { $rejected=$true }
        # THEN unsupported state is rejected and validation preserves configuration bytes.
        if ($rejected -ne $Reject) { $failures.Add("$Name (expected rejection: $Reject; actual: $rejected)") }
        if ((Get-FileHash "$root/compose.json").Hash -ne $before) { $failures.Add("$Name changed configuration") }
        if (-not $Reject -and -not $rejected -and $context.Image -ne $config.services.app.image) { $failures.Add("$Name selected wrong image") }
    }
    Test-ValidationCase 'Original generated installation' {} $false
    Test-ValidationCase 'Ready installation' { $state.Status='ReadyForBrowserVerification' } $false
    Test-ValidationCase 'Mutable app image' { $config.services.app.image='workbench:latest' }
    Test-ValidationCase 'Divergent worker image' { $config.services.worker.image='sha256:' + ('b' * 64) }
    Test-ValidationCase 'Mutable SQL image' { $config.services.sql.image='sql:latest' }
    Test-ValidationCase 'Failed setup' { $state.Status='Failed' }
    Test-ValidationCase 'Wrong setup project' { $state.Project='foreign' }
    Test-ValidationCase 'Wrong compose project' { $config.name='foreign' }
    Test-ValidationCase 'Incomplete journal' { $journal=@{Version=1;Status='Running'} }
    Test-ValidationCase 'Mismatched successful journal image' { $journal=@{Version=1;Status='Succeeded';Project=$project;Image='sha256:' + ('b' * 64);SourceRevision=$state.SourceRevision} }
    Test-ValidationCase 'Mismatched successful journal project' { $journal=@{Version=1;Status='Succeeded';Project='foreign';Image=$config.services.app.image;SourceRevision=$state.SourceRevision} }
    Test-ValidationCase 'Invalid successful journal revision' { $journal=@{Version=1;Status='Succeeded';Project=$project;Image=$config.services.app.image;SourceRevision='main'} }
    Test-ValidationCase 'Matching successful journal' { $journal=@{Version=1;Status='Succeeded';Phase='complete';Project=$project;Image=$config.services.app.image;SourceRevision=('b' * 40)} } $false
    Test-ValidationCase 'Custom runtime mount' { $config.services.app.volumes[0].source='foreign' }
    Test-ValidationCase 'Duplicate runtime mounts' { $config.services.app.volumes[1]=$config.services.app.volumes[2] }
    Test-ValidationCase 'Custom SQL storage mount' { $config.services.sql.volumes[0].source='foreign' }
    Test-ValidationCase 'Custom named volume mapping' { $config.volumes.blobs=@{external=$true;name='foreign'} }
    Test-ValidationCase 'Custom storage provider' { $config.services.app.environment.Storage__Provider='AzureBlob' }
    Test-ValidationCase 'Custom connection file' { $config.services.app.environment.ConnectionStrings__WorkbenchFile='/run/secrets/other' }
    Test-ValidationCase 'Custom runtime network' { $config.services.app.networks=@('foreign') }
    Test-ValidationCase 'Foreign network attachment' { $foreignNetwork=$true }
    Test-ValidationCase 'Foreign volume ownership' { $wrongVolumeOwner=$true }
    Test-ValidationCase 'Foreign network ownership' { $wrongNetworkOwner=$true }
    Test-ValidationCase 'Foreign maintenance SQL server' { [IO.File]::WriteAllText("$root/secrets/maintenance-connection",$originalConnections.maintenance.Replace('tcp:sql,1433','tcp:foreign,1433')) }
    Test-ValidationCase 'Wrong migrator SQL role' { [IO.File]::WriteAllText("$root/secrets/migrator-connection",$originalConnections.migrator.Replace('workbench_migrator_local','sa')) }
    # GIVEN an installation operation already owns the lock, WHEN a second updater starts,
    # THEN it refuses before build, downtime, or any credential/configuration mutation.
    $lock = [IO.File]::Open("$root/update.lock",[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)
    try {
        $lockRejected=$false
        try { & "$PSScriptRoot/update-local-self-host.ps1" -InstallationRoot $root -SourceRef HEAD -Confirmation 'UPDATE Workbench' } catch { $lockRejected=$_.Exception.Message -like '*holds update.lock*' }
        if (-not $lockRejected) { $failures.Add('Concurrent updater was not rejected at the operation lock') }
    } finally { $lock.Dispose() }
    # GIVEN an unconfirmed invocation, WHEN the entrypoint runs, THEN it refuses before an operation.
    $confirmationRejected=$false
    try { & "$PSScriptRoot/update-local-self-host.ps1" -InstallationRoot $root -SourceRef HEAD -Confirmation 'update' } catch { $confirmationRejected=$_.Exception.Message -like '*authorize downtime*' }
    if (-not $confirmationRejected) { $failures.Add('Missing confirmation was accepted') }
    & {
        . "$PSScriptRoot/local-self-host/Update.ps1"
        function Invoke-LocalDocker($Docker, $Arguments) { foreach ($service in @('app','worker','sql','proxy')) { "$service $('a' * 64)" } }
        function Get-UpdateContainers($Context) {
            foreach ($service in @('app','worker','sql','proxy')) {
                [pscustomobject]@{Config=[pscustomobject]@{Labels=[pscustomobject]@{'com.docker.compose.service'=$service;'com.docker.compose.config-hash'=$(if ($mismatch -and $service -eq 'proxy') {'b' * 64} else {'a' * 64})}}}
            }
        }
        # GIVEN the saved configuration matches all running service hashes, THEN preflight accepts it.
        $mismatch=$false
        Assert-UpdateConfigurationCurrent @{Docker='fake';Compose=@('compose')}
        # WHEN a running proxy differs, THEN checkpointing a different volume layout is rejected.
        $mismatch=$true; $rejected=$false
        try { Assert-UpdateConfigurationCurrent @{Docker='fake';Compose=@('compose')} } catch { $rejected=$true }
        if (-not $rejected) { throw 'Running configuration divergence was accepted.' }
    }
    if ($failures.Count) { throw ($failures -join "`n") }
    Write-Host "Local update validation checks passed ($cases cases; simulated Docker and HTTPS)."
} finally {
    $env:PATH=$oldPath
    $env:WB_SETUP_FIXTURE_ROOT=$oldFixture
    $resolved = [IO.Path]::GetFullPath($fixture)
    if ((Split-Path $resolved -Leaf) -notmatch '^workbench-update-validation-[a-f0-9]{32}$' -or (Split-Path $resolved -Parent) -ne [IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\')) { throw 'Unsafe validation fixture cleanup path.' }
    Remove-Item -LiteralPath $resolved -Recurse -Force
}
